# Generated by Django 4.1.1 on 2022-09-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyKnitting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeedlesForProject',
        ),
    ]
